### ISSUE TITLE
works on some videos but not all

### ISSUE THREAD

**Issue by nvlis** [krushil1/EdPuzzle-Fastforward#1]
says VM478:3 Uncaught TypeError: Illegal invocation
    at <anonymous>:3:81
when i try to use the script on a video

**Comment by krushil1** [comment]
I see what you exactly mean, you get that error when you just paste the script and not select the EdPuzzle's video iframe. Watch the screen recording I created by simply clicking on the link I added below to see how to properly use the script! My school uses Schoology for EdPuzzle, but this script works just as well as it does on the regular EdPuzzle site! [Click here for the screen recording video](https://filebin.net/aoxnx9djcvlk0cdm/Screen_Recording_2021-04-22_at_3.50.54_PM.mp4?t=opr20ib8)

**Comment by krushil1** [comment]
It will make a popup and ask you to download, just click on the download button, it actually won't download the video, it will just launch the video!
